/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iguanatool_casestudies_line_intersect_testobjects_line_intersect */

#ifndef _Included_org_iguanatool_casestudies_line_intersect_testobjects_line_intersect
#define _Included_org_iguanatool_casestudies_line_intersect_testobjects_line_intersect
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iguanatool_casestudies_line_intersect_testobjects_line_intersect_TEST_OBJECT_ID
#define org_iguanatool_casestudies_line_intersect_testobjects_line_intersect_TEST_OBJECT_ID 0L
/*
 * Class:     org_iguanatool_casestudies_line_intersect_testobjects_line_intersect
 * Method:    call
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_iguanatool_casestudies_line_1intersect_testobjects_line_1intersect_call
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
