/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iguanatool_casestudies_calendar_testobjects_days_between */

#ifndef _Included_org_iguanatool_casestudies_calendar_testobjects_days_between
#define _Included_org_iguanatool_casestudies_calendar_testobjects_days_between
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iguanatool_casestudies_calendar_testobjects_days_between_TEST_OBJECT_ID
#define org_iguanatool_casestudies_calendar_testobjects_days_between_TEST_OBJECT_ID 0L
/*
 * Class:     org_iguanatool_casestudies_calendar_testobjects_days_between
 * Method:    call
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_iguanatool_casestudies_calendar_testobjects_days_1between_call
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
