/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iguanatool_casestudies_calendar_testobjects_is_leap_year */

#ifndef _Included_org_iguanatool_casestudies_calendar_testobjects_is_leap_year
#define _Included_org_iguanatool_casestudies_calendar_testobjects_is_leap_year
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iguanatool_casestudies_calendar_testobjects_is_leap_year_TEST_OBJECT_ID
#define org_iguanatool_casestudies_calendar_testobjects_is_leap_year_TEST_OBJECT_ID 1L
/*
 * Class:     org_iguanatool_casestudies_calendar_testobjects_is_leap_year
 * Method:    call
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_iguanatool_casestudies_calendar_testobjects_is_1leap_1year_call
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
