/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iguanatool_casestudies_calendar_testobjects_month_days */

#ifndef _Included_org_iguanatool_casestudies_calendar_testobjects_month_days
#define _Included_org_iguanatool_casestudies_calendar_testobjects_month_days
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iguanatool_casestudies_calendar_testobjects_month_days_TEST_OBJECT_ID
#define org_iguanatool_casestudies_calendar_testobjects_month_days_TEST_OBJECT_ID 2L
/*
 * Class:     org_iguanatool_casestudies_calendar_testobjects_month_days
 * Method:    call
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_iguanatool_casestudies_calendar_testobjects_month_1days_call
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
